global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs: 
      - targets: ['localhost:9090'] # URL
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['localhost:9100'] # URL
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['localhost:8080'] # URL
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093'] # URL