global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090'] # URL localhost:9090
  - job_name: 'node-exporter' 
    scrape_interval: 15s 
    static_configs: 
      - targets: ['node-exporter:9100'] # URL
  - job_name: 'cAdvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080'] # URL
  - job_name: 'loki'
    scrape_interval: 10s
    static_configs:
      - targets: ['loki:3100'] # URL
  - job_name: 'promtail'
    scrape_interval: 10s
    static_configs:
      - targets: ['promtail:9080']      
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets: ['alertmanager:9093'] # URL